config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :set_person, only: [:show, :update, :edit, :destroy]
  
  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
    render partial: "form"
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @person.update(person_params)
      redirect_to @person
    else
      render :edit
    end
  end

  def destroy
    @person.destroy
    redirect_to root_path
  end


  private
    def person_params
      params.require(:person).permit[:name]
    end

    def set_person
      @person = Person.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsModel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<fieldset> 
<legend><h1><%= @person.id ? "Edit Person" : "Create Person" %></h1></legend>

<%= form_for @person do |f| %>
    &nbsp;<%= f.label :name %><br>
    <%= f.text_field :name, required: true %><br><br>

    &nbsp;<%= f.label :age %><br>
    <%= f.text_field :age, required: true %><br><br>

    &nbsp;<%= f.label :hair_color %><br>
    <%= f.text_field :hair_color %><br><br>

    &nbsp;<%= f.label :eye_color %><br>
    <%= f.text_field :eye_color %><br><br>

    &nbsp;<%= f.label :gender %><br>
    &emsp;<%= f.radio_button :gender, 'male' %> Male &emsp;
    <%= f.radio_button :gender, 'female' %> Female &emsp;
    <%= f.radio_button :gender, 'other' %> Other <br><br>

    &nbsp;<%= f.label :alive %><br>
    &emsp;<%= f.radio_button :alive, 'yes' %> Yes &emsp;
    &emsp;<%= f.radio_button :alive, 'no' %> No<br><br>

    <%= f.submit %>
<% end %>
</fieldset>

<style>
legend{
    text-align: center;
    color: #4CAF50;
}
fieldset{
    width: 50%;
    font-size: 20px;
    background-color: #f2f2f2;
}
input[type=text]{
    width: 500px;
    padding: 12px 20px;
    margin 8px 0px;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=submit] {
    width: 500px;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 20px;
    font-weight: bold;
</style>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1>PEOPLE</h1>

<div class="addPerson">
<%= link_to 'Add Person', new_person_path %><br>
</div><br>

<% @people.each do |person| %>
    <%= link_to person.name, person %><br>
<% end %>


<style>

.addPerson{
    font-size: 20px;
    color: Green;
    border: 1px red solid;
    width: 144px;
    font-family: "Times New Roman", Times, serif;
    
}

a:link, a:visited {
    background-color: #f44336;
    color: white;
    padding: 14px 25px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
}


a:hover, a:active {
    background-color: red;
}

</style>

app/views/people/new.html.erb
<h1>People Form</h1>

<%= form_for.each do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name, required: true "\n" %>

    <%= f.label :age %>
    <%= f.text_field :age, required: true %>

    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>

    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>

    <%= f.label :gender %>
    <%= f.text_field :gender, required: true%>

    <%= f.label :alive %>
    <%= f.text_field :alive %>

    <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>

<%= link_to 'View Person', person_path(@person) %>
<%= link_to 'Edit Person', edit_person_path(@person) %>
<%= link_to 'Delete Person', @person, method: :delete %>

<style>


a:link, a:visited {
    background-color: #f44336;
    color: white;
    padding: 14px 25px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
}


a:hover, a:active {
    background-color: red;
}

</style>